{-

Haskell/Yampa code for model sir

Generated by Frabjous, developed at the University of Saskatchewan by
	Oliver Schneider,
	Christopher Dutchyn,
	Nathaniel Osgood

-}

{-# LANGUAGE Arrows #-}

module Model_sir where

import Frabjous
import FRP.Yampa


-- network definitions

data Network =	Network_connections
	deriving(Show, Eq)


-- data definition for diagrams

data Diagram_flu =	State_flu_susceptible
			| State_flu_infected
			| State_flu_recovered
	deriving(Show, Eq)



-- state definitions for diagram flu
diagram_flu = state_flu_susceptible

state_flu_susceptible = state output transitions
	where
		output = State_flu_susceptible
		transitions = transition1
		transition1 = receive "infect" state_flu_susceptible

state_flu_infected = state output transitions
	where
		output = State_flu_infected
		transitions = transition1
		transition1 = timeout 10.0 state_flu_infected

state_flu_recovered = state output transitions
	where
		output = State_flu_recovered
		transitions = never -- no transitions from this state



